# Define target output
target: bit

# Define target part
export PRJ_PART = xczu48dr-ffvg1517-2-e

# Define TOP directory
export TOP_DIR = $(abspath $(PWD)/../..)

# Use top level makefile
include ../shared_version.mk
include $(TOP_DIR)/submodules/ruckus/system_vivado.mk
