Root:
  Hardware:
    GpioPs:
      ################
      LMK_RST_OUT: 0x0
      PS_LED1_OUT: 0x0
      PS_LED0_OUT: 0x1
      ################
      LMK_RST_DIR: 0x1
      PS_LED1_DIR: 0x1
      PS_LED0_DIR: 0x1
      ################
      LMK_RST_OEN: 0x1
      PS_LED1_OEN: 0x1
      PS_LED0_OEN: 0x1
      ################
    SpiBridge:
      Regs:
        # BAUD_RATE_DIV: div64
        BAUD_RATE_DIV: div256
    Lmk:
      enable: True
    Lmx[:]:
      enable: True 
      # MUXOUT_LD_SEL: 0x1
  RFSoC4x2:
    enable: True
    Application:
      AppRingBuffer:
        Adc:
          Ch[:]:
            TrigBurst: 0x0
            ContinuousMode: 0x1
        Dac:
          Ch[:]:
            TrigBurst: 0x0
            ContinuousMode: 0x1
      # DacSigGen:
        # enable: True
        # Enabled: 0x1
        # Continuous: 0x1
        # # CsvFilePath: 'config/DacSigGen/1tone_19_531250MHz_all_channels.csv'
        # # CsvFilePath: 'config/DacSigGen/1tone_21MHz.csv'
        # # CsvFilePath: 'config/DacSigGen/1tone_1GHz.csv'
        # # CsvFilePath: 'config/DacSigGen/2tone_1GHz_1MHzspacing.csv'
        # CsvFilePath: 'config/DacSigGen/Ntone_2GHz_blanksection.csv'
        # # CsvFilePath: 'config/DacSigGen/zero_all_ch.csv'
